"""initial production schema

Revision ID: 20260719_0001
Revises:
Create Date: 2026-07-19 23:54:04.032141
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260719_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('configuration_version', sa.String(length=32), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('directional_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('market_risk_score', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_score_series_time', 'ai_score_snapshots', ['instrument', 'timeframe', 'as_of'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_as_of'), 'ai_score_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_instrument'), 'ai_score_snapshots', ['instrument'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_mode'), 'ai_score_snapshots', ['mode'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_policy_version'), 'ai_score_snapshots', ['policy_version'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_status'), 'ai_score_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_ai_score_snapshots_timeframe'), 'ai_score_snapshots', ['timeframe'], unique=False)
    op.create_index('ux_ai_score_fingerprint_mode', 'ai_score_snapshots', ['input_fingerprint', 'mode'], unique=True)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_created_at'), 'analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_engine'), 'analysis_results', ['engine'], unique=False)
    op.create_index(op.f('ix_analysis_results_symbol'), 'analysis_results', ['symbol'], unique=False)
    op.create_table('economic_calendar_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('configuration_version', sa.String(length=32), nullable=False),
    sa.Column('normalization_version', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('state_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_checkpoints_created_at'), 'economic_calendar_checkpoints', ['created_at'], unique=False)
    op.create_index('ux_economic_calendar_checkpoint_engine', 'economic_calendar_checkpoints', ['engine_name', 'configuration_version'], unique=True)
    op.create_table('economic_calendar_event_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('revision_type', sa.String(length=32), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_event_revisions_available_at'), 'economic_calendar_event_revisions', ['available_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_event_revisions_event_id'), 'economic_calendar_event_revisions', ['event_id'], unique=False)
    op.create_index(op.f('ix_economic_calendar_event_revisions_payload_hash'), 'economic_calendar_event_revisions', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_economic_calendar_event_revisions_revision_type'), 'economic_calendar_event_revisions', ['revision_type'], unique=False)
    op.create_index('ux_economic_calendar_revision_number', 'economic_calendar_event_revisions', ['event_id', 'revision_number'], unique=True)
    op.create_table('economic_calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('currency_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration_version', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_events_available_at'), 'economic_calendar_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_canonical_name'), 'economic_calendar_events', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_category'), 'economic_calendar_events', ['category'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_country_code'), 'economic_calendar_events', ['country_code'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_importance'), 'economic_calendar_events', ['importance'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_scheduled_at'), 'economic_calendar_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_events_status'), 'economic_calendar_events', ['status'], unique=False)
    op.create_table('economic_calendar_instrument_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('historical_boundary', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_instrument_contexts_historical_boundary'), 'economic_calendar_instrument_contexts', ['historical_boundary'], unique=False)
    op.create_index(op.f('ix_economic_calendar_instrument_contexts_symbol'), 'economic_calendar_instrument_contexts', ['symbol'], unique=False)
    op.create_table('economic_calendar_provider_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=256), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_provider_observations_available_at'), 'economic_calendar_provider_observations', ['available_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_provider_observations_ingested_at'), 'economic_calendar_provider_observations', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_provider_observations_payload_hash'), 'economic_calendar_provider_observations', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_economic_calendar_provider_observations_provider_event_id'), 'economic_calendar_provider_observations', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_economic_calendar_provider_observations_provider_name'), 'economic_calendar_provider_observations', ['provider_name'], unique=False)
    op.create_table('economic_calendar_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('historical_boundary', sa.DateTime(timezone=True), nullable=False),
    sa.Column('configuration_version', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_snapshots_analysis_timestamp'), 'economic_calendar_snapshots', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('ix_economic_calendar_snapshots_created_at'), 'economic_calendar_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_economic_calendar_snapshots_historical_boundary'), 'economic_calendar_snapshots', ['historical_boundary'], unique=False)
    op.create_table('economic_calendar_sync_state',
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_name')
    )
    op.create_index(op.f('ix_economic_calendar_sync_state_updated_at'), 'economic_calendar_sync_state', ['updated_at'], unique=False)
    op.create_table('engine_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_logs_created_at'), 'engine_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_engine_logs_engine'), 'engine_logs', ['engine'], unique=False)
    op.create_table('historical_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_level', sa.String(length=32), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_candles_provider'), 'historical_candles', ['provider'], unique=False)
    op.create_index(op.f('ix_historical_candles_symbol'), 'historical_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_candles_timeframe'), 'historical_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_historical_candles_timestamp'), 'historical_candles', ['timestamp'], unique=False)
    op.create_index('ux_historical_candle_series', 'historical_candles', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.create_table('institutional_flow_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('configuration_version', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('last_processed_candle', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('state_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_flow_checkpoints_last_processed_candle'), 'institutional_flow_checkpoints', ['last_processed_candle'], unique=False)
    op.create_index(op.f('ix_institutional_flow_checkpoints_snapshot_id'), 'institutional_flow_checkpoints', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_institutional_flow_checkpoints_symbol'), 'institutional_flow_checkpoints', ['symbol'], unique=False)
    op.create_index(op.f('ix_institutional_flow_checkpoints_timeframe'), 'institutional_flow_checkpoints', ['timeframe'], unique=False)
    op.create_index('ux_institutional_flow_checkpoint_series', 'institutional_flow_checkpoints', ['symbol', 'timeframe', 'configuration_version'], unique=True)
    op.create_table('institutional_flow_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('source_engine', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=